"""
Unit and integration tests for Bob Fab synthetic data generation engine.
Uses standard library unittest for zero-dependency test execution.
"""

import math
import sqlite3
import unittest
import tempfile
from pathlib import Path

from data.config import SCENARIOS_CONFIG, PROCESS_SPECS
from data.spatial_patterns import (
    generate_edge_ring,
    generate_center_cluster,
    generate_scratch,
    generate_donut,
    generate_random_background,
)
from data.lot_generator import generate_full_synthetic_dataset
from data.db import init_database, insert_synthetic_data


class TestDataGeneration(unittest.TestCase):
    def test_spatial_patterns_within_unit_disk(self):
        """Verify that 100% of points generated by all patterns lie strictly within the wafer disk."""
        for generator in [
            generate_edge_ring,
            generate_center_cluster,
            generate_scratch,
            generate_donut,
            generate_random_background,
        ]:
            points = generator(200)
            self.assertEqual(len(points), 200)
            for x, y in points:
                r_sq = x * x + y * y
                self.assertLessEqual(r_sq, 1.0001, f"Point ({x}, {y}) is outside unit disk (r^2 = {r_sq})")

    def test_spatial_radial_characteristics(self):
        """Verify statistical radial characteristics of specific signatures."""
        edge_points = generate_edge_ring(300)
        edge_radii = [math.sqrt(x * x + y * y) for x, y in edge_points]
        self.assertGreater(sum(edge_radii) / len(edge_radii), 0.75)

        center_points = generate_center_cluster(300)
        center_radii = [math.sqrt(x * x + y * y) for x, y in center_points]
        self.assertLess(sum(center_radii) / len(center_radii), 0.35)

    def test_full_dataset_generation_and_seeding(self):
        """Test end-to-end dataset synthesis, SQLite schema initialization, and ingestion."""
        with tempfile.TemporaryDirectory() as tmp_dir:
            test_db = Path(tmp_dir) / "test_bob_fab.db"

            # 1. Generate dataset
            data = generate_full_synthetic_dataset(seed=999)
            self.assertEqual(len(data["wafer_lots"]), 119)
            self.assertEqual(len(data["ground_truth_labels"]), 74)
            self.assertGreater(len(data["process_steps"]), 500)
            self.assertGreater(len(data["defects"]), 50000)

            # 2. Init DB and Insert
            init_database(db_path=test_db)
            counts = insert_synthetic_data(data, db_path=test_db)
            self.assertEqual(counts["wafer_lots"], 119)
            self.assertEqual(counts["ground_truth_labels"], 74)

            # 3. Check foreign keys
            conn = sqlite3.connect(str(test_db))
            cur = conn.cursor()
            cur.execute("PRAGMA foreign_key_check;")
            violations = cur.fetchall()
            self.assertEqual(len(violations), 0)

            # 4. Verify in-progress null yields
            cur.execute("SELECT final_yield_pct FROM wafer_lots WHERE status IN ('in_progress', 'at_risk');")
            ip_yields = [row[0] for row in cur.fetchall()]
            self.assertTrue(all(y is None for y in ip_yields))

            conn.close()


if __name__ == "__main__":
    unittest.main()
